services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./dockerfile/client.Dockerfile
    ports:
      - 3000:3000 
    networks:
      - hadoop      

  hadoop:    
    container_name: hadoop
    build:
      context: ./
      dockerfile: ./dockerfile/hadoop.Dockerfile
    ports:
      - 9870:9870
      - 9000:9000
      - 8088:8088
      - 9864:9864      
    volumes:      
      - ./data:/csv:rw      
    hostname: hadoop
    environment:
      - CLUSTER_NAME=hadoop-cluster
    networks:
      - hadoop      

  spark-master:
    container_name: spark-master
    build:
      context: ./
      dockerfile: ./dockerfile/spark.Dockerfile    
    hostname: spark-master
    ports:
      - "8080:8080"  
      - "7077:7077"
      - "4040:4040"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077 
      - SPARK_LOCAL_HOSTNAME=spark-master   
    volumes:      
      - ./jobs:/opt/bitnami/spark/jobs
      - ./secrets/spark-gcloud-key.json:/opt/bitnami/spark/secrets/spark-gcloud-key.json                                        
      - ./config/spark/log4j.properties:/opt/bitnami/spark/conf/log4j.properties      
      #- ./jars:/opt/bitnami/spark/custom-jars       
      # - ./config/spark/spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh  
    networks:
      - hadoop        

  spark-worker:
    image: custom-spark-gcs #bitnami/spark:3.5.2
    container_name: spark-worker
    build:
      context: ./
      dockerfile: ./dockerfile/spark.Dockerfile   
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2 
    volumes:
      - ./secrets/spark-gcloud-key.json:/opt/bitnami/spark/secrets/spark-gcloud-key.json
      - ./jars:/opt/bitnami/spark/custom-jars      
      - ./config/spark/log4j.properties:/opt/bitnami/spark/conf/log4j.properties      
    networks:
      - hadoop
      
networks:
  hadoop:
    driver: bridge
